import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"; // Importiert die Schriftarten für modernes Design
import "./globals.css"; // Importiert die globalen Styles
import Header from "./ui/header"; // Importiert den Header für globalen Header
import Footer from "./ui/footer"; // Importiert den Footer für globalen Footer

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({ 
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ger">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header></Header>
        <main>{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
